# Generated by Django 5.0.7 on 2024-07-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
