# Generated by Django 4.2.14 on 2024-07-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adboard', '0002_alter_advertisement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
