# Generated by Django 4.2.14 on 2024-07-16 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adboard', '0005_adreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='responses',
            field=models.ManyToManyField(related_name='advertisements', through='adboard.AdReply', to=settings.AUTH_USER_MODEL),
        ),
    ]
