# Generated by Django 4.2.14 on 2024-07-16 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adboard', '0006_advertisement_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='responses',
            field=models.ManyToManyField(related_name='userresponses', through='adboard.AdReply', to=settings.AUTH_USER_MODEL),
        ),
    ]
